/**
 * Consumer contrast-contract baseline — the KNOWN violations as of
 * 2026-08-21 (ggui#594's measurement matrix; 28 entries, generated by
 * running `validateConsumerContrast` across the registry, not typed by
 * hand).
 *
 * Burn-down rules (enforced by `contrast-contract.test.ts`, both
 * directions):
 *   - A NEW violation (any theme×mode×pair not listed here) fails the
 *     suite — the registry may not get worse.
 *   - A listed entry that STOPS failing also fails the suite until it
 *     is deleted here — fixes must claim their ground so the baseline
 *     only shrinks.
 *
 * Fixing an entry means fixing THEME DATA (a stop or role value that
 * breaks its contract with the consumers), never loosening a
 * threshold; threshold changes require re-adjudicating the pair list
 * in ggui#594.
 */
export interface ContrastBaselineEntry {
  readonly theme: string;
  readonly mode: 'light' | 'dark';
  readonly label: string;
}

export const CONSUMER_CONTRAST_BASELINE: readonly ContrastBaselineEntry[] = [
  { theme: 'ggui', mode: 'light', label: 'slots.negative e500/surface' }, // 4.16:1 (min 4.5) — #d93822 on #f4f3ed
  { theme: 'ggui', mode: 'light', label: 'slots.warning w500/surface' }, // 3.43:1 (min 4.5) — #a87b0e on #f4f3ed
  { theme: 'indigo', mode: 'light', label: 'slots.positive s500/surface' }, // 3.31:1 (min 4.5) — #0e9d6e on #fafaf7
  { theme: 'indigo', mode: 'light', label: 'slots.warning w500/surface' }, // 2.67:1 (min 4.5) — #e08515 on #fafaf7
  { theme: 'indigo', mode: 'dark', label: 'slots.subtle n500/surface' }, // 2.83:1 (min 3) — #5e5c70 on #15131f
  { theme: 'claudic', mode: 'light', label: 'stepper.current onPrimary/bg600' }, // 3.85:1 (min 4.5) — #faf9f5 on #b8694f
  { theme: 'claudic', mode: 'light', label: 'slots.loud p500/surface' }, // 3.11:1 (min 4.5) — #cc785c on #faf9f5
  { theme: 'claudic', mode: 'light', label: 'slots.positive s500/surface' }, // 3.58:1 (min 4.5) — #6b8e3d on #faf9f5
  { theme: 'claudic', mode: 'light', label: 'slots.warning w500/surface' }, // 2.70:1 (min 4.5) — #c98e2e on #faf9f5
  { theme: 'claudic', mode: 'dark', label: 'slots.negative e500/surface' }, // 4.39:1 (min 4.5) — #d56b59 on #262624
  { theme: 'premium-cyberpunk', mode: 'light', label: 'slots.subtle n500/surface' }, // 2.72:1 (min 3) — #55556a on #0a0a0f
  { theme: 'premium-cyberpunk', mode: 'light', label: 'slots.emphasized p700/surface' }, // 3.69:1 (min 4.5) — #0e7490 on #0a0a0f
  { theme: 'premium-cyberpunk', mode: 'dark', label: 'slots.subtle n500/surface' }, // 2.89:1 (min 3) — #55556a on #000005
  { theme: 'premium-zen', mode: 'light', label: 'slots.subtle n500/surface' }, // 2.98:1 (min 3) — #9a9084 on #faf9f7
  { theme: 'premium-zen', mode: 'light', label: 'slots.loud p500/surface' }, // 3.75:1 (min 4.5) — #748660 on #faf9f7
  { theme: 'premium-zen', mode: 'light', label: 'slots.positive s500/surface' }, // 3.49:1 (min 4.5) — #6b8f5e on #faf9f7
  { theme: 'premium-zen', mode: 'light', label: 'slots.warning w500/surface' }, // 2.17:1 (min 4.5) — #c9a84c on #faf9f7
  { theme: 'premium-zen', mode: 'dark', label: 'slots.negative e500/surface' }, // 4.34:1 (min 4.5) — #cf6f6a on #2a2724
  { theme: 'premium-neon-noir', mode: 'light', label: 'stepper.current onPrimary/bg600' }, // 4.33:1 (min 4.5) — #09090b on #db2777
  { theme: 'premium-neon-noir', mode: 'light', label: 'slots.subtle n500/surface' }, // 2.93:1 (min 3) — #5a5a68 on #09090b
  { theme: 'premium-neon-noir', mode: 'light', label: 'slots.emphasized p700/surface' }, // 3.30:1 (min 4.5) — #be185d on #09090b
  { theme: 'premium-botanical', mode: 'light', label: 'stepper.current onPrimary/bg600' }, // 3.22:1 (min 4.5) — #fefcf8 on #16a34a
  { theme: 'premium-botanical', mode: 'light', label: 'slots.subtle n500/surface' }, // 2.21:1 (min 3) — #bfaa80 on #fefcf8
  { theme: 'premium-botanical', mode: 'light', label: 'slots.loud p500/surface' }, // 2.22:1 (min 4.5) — #22c55e on #fefcf8
  { theme: 'premium-botanical', mode: 'light', label: 'slots.positive s500/surface' }, // 2.22:1 (min 4.5) — #22c55e on #fefcf8
  { theme: 'premium-botanical', mode: 'light', label: 'slots.negative e500/surface' }, // 3.67:1 (min 4.5) — #ef4444 on #fefcf8
  { theme: 'premium-botanical', mode: 'light', label: 'slots.warning w500/surface' }, // 2.10:1 (min 4.5) — #f59e0b on #fefcf8
  { theme: 'guuey-brand-v1', mode: 'light', label: 'slots.loud p500/surface' }, // 1.60:1 (min 4.5) — #9FE01C on #FFFFFF
];
