#!/usr/bin/env node
// The social card's renderer digest: a sha256 over every file that shapes the
// card's pixels (the renderer's sources and the face files), in a fixed order.
// `socialCardKey` folds it into each card's key, so a renderer change moves
// every key. Run `pnpm --filter @ggui-ai/brand generate:digest` after changing
// any listed file; `card-key.test.ts` fails until the committed digest matches.
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * The renderer's inputs, relative to the package root. A test checks that
 * this list holds every module the renderer imports, so a new module cannot
 * change the card without moving the digest.
 */
export const RENDERER_INPUTS = [
  'src/social-card.ts',
  'src/node.ts',
  'src/tokens.ts',
  'src/wordmark.ts',
  'src/fonts.ts',
  'fonts/Inter-Regular.woff',
  'fonts/Inter-Bold.woff',
  'fonts/GeistMono-Regular.woff',
];

/** The digest over {@link RENDERER_INPUTS}, read from `packageDir`. */
export function computeRendererDigest(packageDir) {
  const hash = createHash('sha256');
  for (const path of RENDERER_INPUTS) {
    const bytes = readFileSync(join(packageDir, path));
    hash.update(`${path}\0${bytes.length}\0`);
    hash.update(bytes);
  }
  return hash.digest('hex');
}

/** The committed module that carries the digest. */
export function renderDigestModule(digest) {
  return [
    '// Generated by scripts/renderer-digest.mjs. Do not edit: run',
    '// `pnpm --filter @ggui-ai/brand generate:digest` after changing the renderer.',
    '',
    '/** A sha256 over the social card renderer\'s sources and face files. */',
    `export const SOCIAL_CARD_RENDERER_DIGEST = '${digest}';`,
    '',
  ].join('\n');
}

const packageDir = join(dirname(fileURLToPath(import.meta.url)), '..');
if (process.argv[1] !== undefined && fileURLToPath(import.meta.url) === process.argv[1]) {
  const digest = computeRendererDigest(packageDir);
  writeFileSync(join(packageDir, 'src/renderer-digest.ts'), renderDigestModule(digest));
  console.log(`renderer digest ${digest}`);
}
