/**
 * `config-push` — read `ggui.json#app.{gadgets,publicEnv}` and
 * `ggui.json#generation`, guard against loopback bundle URLs, and PATCH the
 * cloud app config via the REST API.
 *
 * Consumed by `ggui deploy` (M3.3) — wiring into that command is a separate
 * task. This module is the pure logic layer: readers + guard + network call.
 */
import process from 'node:process';
import { dirname } from 'node:path';
import {
  strictGadgetDescriptorSchema,
  appPublicEnvSchema,
  appThemeSchema,
  LOOPBACK_HOST_RE,
  type GadgetDescriptor,
  type AppTheme,
} from '@ggui-ai/protocol';
import { loadTheme, parseGguiJson } from '@ggui-ai/project-config/node';
import { z } from 'zod';
import { patchAppConfig } from './api-client.js';
import { findGguiJson, readGguiJson } from './internal/ggui-json.js';

// ─────────────────────────────────────────────────────────────────────────────
// Readers
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Extract and validate `app.gadgets` from a decoded ggui.json value.
 *
 * Returns `[]` when the field is absent.
 * Throws with a descriptive message when any descriptor is malformed
 * (schema parse fails).
 */
export function readGadgetsFromGguiJson(gguiJson: unknown): GadgetDescriptor[] {
  // Navigate to `app.gadgets` via a nested schema rather than casting +
  // index access. `z.object` is non-strict by default, so ggui.json's other
  // fields (schema / protocol / generation / app.publicEnv / …) ride through
  // as allowed-and-stripped extras — only `app.gadgets` is validated here.
  const schema = z.object({
    app: z
      .object({
        gadgets: z.array(strictGadgetDescriptorSchema).optional(),
      })
      .optional(),
  });
  const result = schema.safeParse(gguiJson);
  if (!result.success) {
    throw new Error(
      `ggui.json: app.gadgets is invalid — ${result.error.issues[0]?.message ?? 'malformed descriptor'}`,
    );
  }
  // result.data.app?.gadgets is GadgetDescriptor[] — strictGadgetDescriptorSchema
  // parses to the same shape as GadgetDescriptor. Spread to a fresh mutable array.
  return [...(result.data.app?.gadgets ?? [])];
}

/**
 * Extract and validate `app.publicEnv` from a decoded ggui.json value.
 *
 * Returns `{}` when the field is absent.
 * Throws with a descriptive message when any key/value is invalid.
 * Keys must match `PUBLIC_ENV_APP_KEY_RE` (`GGUI_PUBLIC_APP_<NAME>`).
 */
export function readPublicEnvFromGguiJson(gguiJson: unknown): Record<string, string> {
  // Navigate to `app.publicEnv` via a nested schema (same posture as
  // readGadgetsFromGguiJson) — other ggui.json fields ride through as
  // allowed-and-stripped extras; only `app.publicEnv` is validated here.
  const schema = z.object({
    app: z
      .object({
        publicEnv: appPublicEnvSchema.optional(),
      })
      .optional(),
  });
  const result = schema.safeParse(gguiJson);
  if (!result.success) {
    throw new Error(
      `ggui.json: app.publicEnv is invalid — keys must match GGUI_PUBLIC_APP_<NAME>: ${result.error.issues[0]?.message ?? 'invalid entry'}`,
    );
  }
  // appPublicEnvSchema returns a readonly record; spread to a fresh mutable one.
  return { ...(result.data.app?.publicEnv ?? {}) };
}

/**
 * Extract and validate `generation` from a decoded ggui.json value.
 *
 * Reads the RAW model string (not a resolved `LlmRoute`) — the cloud
 * re-validates via `parseAnyLlmRoute` server-side; the CLI just forwards.
 *
 * Returns `{ model, keySource }` when `generation.model` is present.
 * Returns `undefined` when the generation block is absent or has no model.
 * Throws when the generation block is structurally invalid.
 */
export function readGenerationFromGguiJson(
  gguiJson: unknown,
): { model: string; keySource: 'own' | 'managed' } | undefined {
  const schema = z.object({
    generation: z
      .object({
        model: z.string().min(1).optional(),
        keySource: z.enum(['own', 'managed']).optional(),
      })
      .optional(),
  });
  const result = schema.safeParse(gguiJson);
  if (!result.success) {
    throw new Error(
      `ggui.json: generation is invalid — ${result.error.issues[0]?.message ?? 'malformed generation block'}`,
    );
  }
  const model = result.data.generation?.model;
  if (!model) return undefined;
  return { model, keySource: result.data.generation?.keySource ?? 'managed' };
}

/**
 * Parse a generated `:root { --ggui-x: val; … }` block into a flat
 * `{ '--ggui-x': 'val' }` map.
 *
 * The block is machine-generated by `@ggui-ai/design`'s theme parser
 * (one `--ggui-*: value;` declaration per line, wrapped in a `:root {…}`
 * selector), so a line-based parse is deterministic:
 *   - split on newlines;
 *   - on each line, split at the FIRST `:` (custom-property names never
 *     contain `:`, so the key is unambiguous even when the value does);
 *   - keep only `--ggui-*`-prefixed keys with a non-empty value. The
 *     `:root {` and `}` wrapper lines have no such key and drop out.
 */
function parseCssVarBlock(css: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const line of css.split('\n')) {
    const i = line.indexOf(':');
    if (i === -1) continue;
    const key = line.slice(0, i).trim();
    let val = line.slice(i + 1).trim();
    if (val.endsWith(';')) val = val.slice(0, -1).trim();
    if (key.startsWith('--ggui-') && val.length > 0) out[key] = val;
  }
  return out;
}

/**
 * Resolve the developer's local `ggui.json#theme` into a concrete,
 * injection-safe {@link AppTheme} ready to PATCH to the cloud.
 *
 * Returns `undefined` when no `theme` field is declared (deploy leaves the
 * app's theme untouched).
 *
 * When a theme IS declared we parse the FULL manifest (via `parseGguiJson`)
 * — `loadTheme` requires the typed `GguiJsonV1` shape and resolves relative
 * `theme.file` paths against `projectRoot`, so a partial slice will not do.
 *
 * Throws with a clear, local message when:
 *   - the manifest is structurally invalid (so deploy fails before the wire);
 *   - the theme cannot be loaded (e.g. an unregistered preset id);
 *   - the resolved overlay fails `appThemeSchema` — the SAME validator the
 *     backend enforces, so a deploy fails loud LOCALLY rather than with a
 *     confusing 422.
 */
export function readThemeFromGguiJson(
  projectRoot: string,
  gguiJson: unknown,
): AppTheme | undefined {
  // Cheap pre-check on the raw value: no `theme` field → nothing to push,
  // and we avoid forcing a full-manifest parse on theme-less deploys.
  const presence = z
    .object({ theme: z.unknown().optional() })
    .safeParse(gguiJson);
  if (!presence.success || presence.data.theme === undefined) return undefined;

  // A theme is declared — `loadTheme` needs the fully-typed manifest.
  let manifest;
  try {
    manifest = parseGguiJson(gguiJson);
  } catch (err) {
    throw new Error(
      `ggui.json: cannot resolve theme — manifest is invalid: ${
        err instanceof Error ? err.message : String(err)
      }`,
    );
  }

  const result = loadTheme({ projectRoot, manifest });
  if (!result.ok) {
    throw new Error(`ggui.json: ${result.issue.message}`);
  }
  const loaded = result.theme;

  const theme: AppTheme = {
    mode: loaded.mode,
    cssVariables: parseCssVarBlock(loaded.cssVariables),
    ...(loaded.source === 'preset' ? { name: loaded.preset } : {}),
  };

  // Defense + clear local error: the resolved overlay must satisfy the same
  // schema the backend enforces, so a deploy fails loud LOCALLY (not with a
  // confusing 422) if a token ever produces an unsafe value.
  const parsed = appThemeSchema.safeParse(theme);
  if (!parsed.success) {
    throw new Error(
      `ggui.json: resolved theme is invalid — ${
        parsed.error.issues[0]?.message ?? 'unexpected css value'
      }`,
    );
  }
  return parsed.data;
}

// ─────────────────────────────────────────────────────────────────────────────
// Loopback guard
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Assert that none of the gadget bundle references point at a loopback host.
 *
 * `LOOPBACK_HOST_RE` matches bare hosts (no scheme, optional `:port`):
 *   - `localhost` / `localhost:3000`
 *   - `127.0.0.1` / `127.0.0.1:8080`
 *   - `0.0.0.0` / `0.0.0.0:4321`
 *
 * Resolution order for "bundle host":
 *   1. `bundleHost` (bare hostname, already scheme-free)
 *   2. `bundleUrl` parsed via `new URL()` → `.host` (includes port)
 *   3. Neither present → gadget has no cloud bundle reference; passes.
 *
 * Throws an `Error` with a remediation hint when a loopback is detected.
 */
export function assertGadgetBundlesReachable(gadgets: GadgetDescriptor[]): void {
  for (const g of gadgets) {
    let host: string | undefined;

    if (g.bundleHost !== undefined) {
      host = g.bundleHost;
    } else if (g.bundleUrl !== undefined) {
      host = new URL(g.bundleUrl).host;
    }

    if (host !== undefined && LOOPBACK_HOST_RE.test(host)) {
      throw new Error(
        `gadget ${g.package}'s bundle is local-only (${host}) — publish it to a ` +
          `cloud-reachable registry (run \`ggui gadget publish\`) before deploy.`,
      );
    }
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Orchestrator
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Find + read `ggui.json`, validate gadgets + publicEnv, guard against
 * loopback bundles, then PATCH the app config via the REST API.
 *
 * @param appId  - The ggui app ID to patch.
 * @param startDir - Optional start directory for `findGguiJson` (defaults to
 *                   `process.cwd()`). Primarily used for testing.
 * @returns 0 on success, 1 on any error (malformed ggui.json, loopback bundle,
 *          network failure). Errors are written to stderr; success summary to
 *          stdout.
 */
export async function runConfigPushStep(
  appId: string,
  startDir: string = process.cwd(),
): Promise<number> {
  const gguiJsonPath = findGguiJson(startDir);
  if (!gguiJsonPath) {
    process.stderr.write(
      'ggui deploy: could not find ggui.json (looked up to 8 parent directories).\n',
    );
    return 1;
  }

  const readResult = readGguiJson(gguiJsonPath);
  if ('error' in readResult) {
    process.stderr.write(`ggui deploy: ${readResult.error}\n`);
    return 1;
  }

  let gadgets: GadgetDescriptor[];
  let publicEnv: Record<string, string>;
  let generation: { model: string; keySource: 'own' | 'managed' } | undefined;
  let theme: AppTheme | undefined;

  try {
    gadgets = readGadgetsFromGguiJson(readResult.value);
  } catch (err) {
    process.stderr.write(
      `ggui deploy: ${err instanceof Error ? err.message : String(err)}\n`,
    );
    return 1;
  }

  try {
    publicEnv = readPublicEnvFromGguiJson(readResult.value);
  } catch (err) {
    process.stderr.write(
      `ggui deploy: ${err instanceof Error ? err.message : String(err)}\n`,
    );
    return 1;
  }

  try {
    generation = readGenerationFromGguiJson(readResult.value);
  } catch (err) {
    process.stderr.write(
      `ggui deploy: ${err instanceof Error ? err.message : String(err)}\n`,
    );
    return 1;
  }

  try {
    // `loadTheme` resolves relative `theme.file` paths against the directory
    // containing ggui.json — the same root convention `storage.*.path` uses.
    theme = readThemeFromGguiJson(dirname(gguiJsonPath), readResult.value);
  } catch (err) {
    process.stderr.write(
      `ggui deploy: ${err instanceof Error ? err.message : String(err)}\n`,
    );
    return 1;
  }

  try {
    assertGadgetBundlesReachable(gadgets);
  } catch (err) {
    process.stderr.write(
      `ggui deploy: ${err instanceof Error ? err.message : String(err)}\n`,
    );
    return 1;
  }

  try {
    await patchAppConfig(appId, {
      gadgets,
      ...(Object.keys(publicEnv).length > 0 ? { publicEnv } : {}),
      ...(generation !== undefined ? { generation } : {}),
      ...(theme !== undefined ? { theme } : {}),
    });
  } catch (err) {
    process.stderr.write(
      `ggui deploy: config push failed — ${err instanceof Error ? err.message : String(err)}\n`,
    );
    return 1;
  }

  const gadgetLine =
    gadgets.length > 0
      ? `pushed ${gadgets.length} gadget extension(s)`
      : 'no gadget extensions — cleared (stdlib still available)';
  const envLine =
    Object.keys(publicEnv).length > 0
      ? ` + ${Object.keys(publicEnv).length} publicEnv key(s)`
      : '';
  const generationLine = generation !== undefined ? ` + model ${generation.model}` : '';
  const themeLine = theme !== undefined ? ` + theme ${theme.name ?? theme.mode}` : '';
  process.stdout.write(`  ${gadgetLine}${envLine}${generationLine}${themeLine}\n`);

  return 0;
}
