/**
 * Sub-tier B — CROSS-DEPLOYMENT seed-pool reuse (the gold-standard gate for the
 * shared-blueprint-pool slice). Proves, against the PUBLISHED `@ggui-ai/*`
 * cohort, that a blueprint generated by ONE ggui deployment is reused by a
 * SEPARATE deployment via `ggui serve --seed-pool <dir>` — NO browser, talking
 * directly to each deployment's ggui MCP server.
 *
 * Two sequential deployments, ONE app at a time (fixed host ports; the harness
 * frees them on close()):
 *
 *   Phase A (deployment A — sqlite vectors): a real cold generation
 *     (forceCreate) mints a durable blueprint and persists it to the on-disk
 *     sqlite vector store. `ggui export-pool` then reads that store and writes a
 *     portable directory artifact (manifest.json + codes/<sha256>.tsx) using the
 *     PUBLISHED `ggui` bin installed in the scaffolded app's servers/ggui.
 *
 *   Phase B (deployment B — seeded, fresh store): a brand-new scaffolded
 *     deployment boots with `--seed-pool <A's artifact>`. The SAME canonical
 *     contract — no forceCreate — must be PROPOSED from the shared pool
 *     (`suggestion.origin === 'cache'`) and the accept render must be a
 *     cross-deployment cache hit (`cache.hit`, `cache.kind === 'full-template'`,
 *     a generation call avoided) carrying the SAME `contractHash` as A.
 *
 * Why no `agentCapabilities` on the contract: a pure-propsSpec UI makes the
 * canonical contract hash trivially deployment-invariant — no tool-identity
 * canonicalization is involved, so the exact-key match is a clean, framework-
 * agnostic proof of the cross-deployment reuse mechanism. The seed pool is
 * EXACT-KEY-ONLY by construction (buildSeedPool wraps the store so semantic
 * `query()` yields nothing), so the contract hash is the load-bearing identity.
 *
 * NOT asserted: blueprintId equality across deployments. `buildSeedPool`
 * re-mints ids on import (shipped keys are advisory), so the reused blueprint
 * carries a fresh id in B. Reuse is proven by origin/hit/kind + the matching
 * contractHash, not by id equality.
 *
 * Auth: the scaffolded ggui runs `ggui serve --mcp-only --dev-allow-all`, which
 * accepts ANY non-empty bearer as `builder`.
 */
import { execFileSync } from 'node:child_process';
import { existsSync, mkdtempSync, readdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { test, expect } from '@playwright/test';
import { spawnScaffoldedApp } from './scaffold-app-harness';
import { renderOnce } from './mcp-turn';

// A niche, pure-propsSpec contract → no built-in blueprint match → the Phase-A
// turn is a genuine cold generation. NO agentCapabilities, so the canonical
// hash is deployment-invariant (no tool-identity canonicalization).
const INTENT = 'A titled list of items for a packing checklist';
const CONTRACT = {
  propsSpec: {
    description: 'a titled list of items',
    properties: {
      title: { schema: { type: 'string' }, required: false },
      items: { schema: { type: 'array', items: { type: 'string' } }, required: false },
    },
  },
} as const;

test.describe('scaffold-render: cross-deployment seed-pool reuse (published app)', () => {
  test.beforeAll(() => {
    test.skip(
      !process.env['ANTHROPIC_API_KEY']?.trim(),
      'set ANTHROPIC_API_KEY — the Phase-A cold generation is a real LLM call',
    );
  });

  test('a blueprint generated by deployment A is reused by deployment B via --seed-pool', async () => {
    // Two full scaffold+install+boot cycles + a real LLM generation in Phase A.
    test.setTimeout(1_500_000);

    // ── Phase A — generate + persist (sqlite) + export the pool ───────────────
    const a = await spawnScaffoldedApp({ sdk: 'claude-agent-sdk', sqliteVectors: true });
    let artifact: string;
    let contractHashA: string;
    try {
      // Cold generation: forceCreate + override.contract STRICT-gens against the
      // fresh draft and mints the durable blueprint, persisted to the on-disk
      // sqlite vector store the next step exports.
      const r1 = await renderOnce(a.gguiUrl, {
        intent: INTENT,
        contract: CONTRACT,
        forceCreate: true,
        override: { contract: CONTRACT },
      });
      // eslint-disable-next-line no-console -- Phase-A generation signal in the CI log.
      console.log(
        `[seed-pool:A] generated bp=${r1.blueprintId} hash=${r1.contractHash} ` +
          `cacheKind=${r1.cache?.kind} ms=${r1.ms}`,
      );
      expect(r1.blueprintId, 'A generated a durable blueprint').toBeTruthy();
      expect(r1.contractHash, 'A render carries a contractHash').toBeTruthy();
      contractHashA = r1.contractHash as string;

      // Export A's pool. The PUBLISHED `ggui` bin is installed in the scaffolded
      // app's servers/ggui node_modules/.bin (its package.json depends on
      // @ggui-ai/cli). `pnpm --filter ./servers/ggui exec` runs with the
      // filtered package's dir as cwd, which is exactly where `ggui export-pool`
      // resolves the storage (ggui.json + the on-disk sqlite vectors store) from.
      artifact = mkdtempSync(join(tmpdir(), 'seed-pool-'));
      execFileSync(
        'pnpm',
        ['--filter', './servers/ggui', 'exec', 'ggui', 'export-pool', '--out', artifact],
        { cwd: a.scaffoldDir, env: { ...process.env }, stdio: 'inherit' },
      );

      // Sanity: the artifact has a manifest + at least one code body. A blueprint
      // that never persisted (sqlite store mis-resolved) would surface here as an
      // empty/absent artifact rather than a confusing Phase-B miss.
      const manifestPath = join(artifact, 'manifest.json');
      const codesDir = join(artifact, 'codes');
      expect(existsSync(manifestPath), 'export-pool wrote a manifest.json').toBe(true);
      expect(existsSync(codesDir), 'export-pool wrote a codes/ dir').toBe(true);
      const codeFiles = readdirSync(codesDir).filter((f) => f.endsWith('.tsx'));
      expect(codeFiles.length, 'the pool artifact carries at least one code body').toBeGreaterThanOrEqual(1);
      // eslint-disable-next-line no-console -- artifact contents signal in the CI log.
      console.log(`[seed-pool:A] exported artifact ${artifact} → ${codeFiles.length} code file(s)`);
    } finally {
      await a.close();
    }

    // ── Phase B — fresh deployment, seeded with A's artifact ──────────────────
    const b = await spawnScaffoldedApp({ sdk: 'claude-agent-sdk', seedPoolDir: artifact });
    try {
      // SAME canonical contract, NOT forceCreate → the handshake must propose
      // A's blueprint from the shared seed pool (exact-key match), and the accept
      // render reuses it cross-deployment.
      const r2 = await renderOnce(b.gguiUrl, {
        intent: INTENT,
        contract: CONTRACT,
        forceCreate: false,
      });
      // eslint-disable-next-line no-console -- cross-deployment reuse signal.
      console.log(
        `[seed-pool:B] origin=${r2.suggestion?.origin} hit=${r2.cache?.hit} ` +
          `kind=${r2.cache?.kind} avoided=${r2.cache?.llmCallsAvoided} ` +
          `bp=${r2.blueprintId} hash=${r2.contractHash} ms=${r2.ms}`,
      );
      // Dump B's captured stdout so the `[ggui:cache-trace]` decision lines (and
      // the --seed-pool load) reach the run log if any assertion below fails.
      // eslint-disable-next-line no-console -- diagnostic dump scoped to this scenario.
      console.log(`[seed-pool:B] scaffolded app output:\n${b.stdout()}`);

      // The handshake proposed the seeded blueprint from the shared pool.
      expect(
        r2.suggestion?.origin,
        'B should propose the seeded blueprint from the shared pool (origin:cache)',
      ).toBe('cache');

      // The accept render is a cross-deployment cache hit reusing the stored
      // template — no cold generation.
      expect(r2.cache?.hit, 'B render should be a cross-deployment cache hit').toBe(true);
      expect(
        r2.cache?.kind,
        'B reused the stored template (full-template, not cold gen)',
      ).toBe('full-template');
      expect(
        r2.cache?.llmCallsAvoided ?? 0,
        'cross-deployment reuse should report a generation call avoided',
      ).toBeGreaterThanOrEqual(1);

      // The canonical contract is identical across deployments — the load-bearing
      // identity that fired the exact-key seed-pool match.
      expect(
        r2.contractHash,
        'B contractHash should EQUAL A (same canonical contract across deployments)',
      ).toBe(contractHashA);
    } finally {
      await b.close();
    }
  });
});
