/**
 * The Anthropic model-family rules (`../anthropic-model-rules`) — moved
 * here with the predicates they pin, from `@ggui-ai/ui-gen`'s router
 * test (ggui#1255/#1264: one list every Anthropic caller imports).
 *
 * Strings per ggui#706's verified table (platform.claude.com,
 * 2026-09-02) — never from memory.
 *
 * The ggui#1268 block at the end pins `anthropicRejectsForcedToolChoice`
 * against a table written from the vendor's pages, over every Anthropic id
 * a route can name. Never snapshot a predicate's output as a fixed list:
 * the table below was written from the pages it cites, not generated by
 * running the predicate, so it can disagree with the predicate. That
 * disagreement is the pin.
 */
import { describe, expect, it } from "vitest";
import {
  anthropicRejectsForcedToolChoice,
  anthropicRejectsSamplingParams,
  normalizeAnthropicModelId,
} from "../anthropic-model-rules.js";
import { BEDROCK_INFERENCE_REGION_PREFIXES, MODELS } from "../llm-route.js";

describe("normalizeAnthropicModelId", () => {
  it("reduces every routing spelling to the bare API id", () => {
    expect(normalizeAnthropicModelId("anthropic/claude-fable-5-1")).toBe("claude-fable-5-1");
    expect(normalizeAnthropicModelId("anthropic.claude-opus-5")).toBe("claude-opus-5");
    expect(normalizeAnthropicModelId("us.anthropic.claude-sonnet-5")).toBe("claude-sonnet-5");
    expect(normalizeAnthropicModelId("us.anthropic.claude-haiku-4-5-20251001-v1:0")).toBe(
      "claude-haiku-4-5-20251001-v1:0"
    );
    expect(normalizeAnthropicModelId("claude-opus-4-7")).toBe("claude-opus-4-7");
  });

  it("leaves ARNs alone (they name a profile, not a family)", () => {
    const arn = "arn:aws:bedrock:us-east-1:123:inference-profile/x";
    expect(normalizeAnthropicModelId(arn)).toBe(arn);
  });
});

describe("anthropicRejectsSamplingParams — Opus 4.7+ and the 5-family", () => {
  it.each([
    "claude-opus-4-7",
    "claude-fable-5",
    "claude-fable-5-1",
    "claude-opus-5",
    "claude-sonnet-5",
    "anthropic/claude-fable-5-1",
    "us.anthropic.claude-opus-5",
    "anthropic.claude-sonnet-5",
  ])("%s rejects sampling params", (id) => {
    expect(anthropicRejectsSamplingParams(id)).toBe(true);
  });

  it.each([
    "claude-haiku-4-5",
    "claude-haiku-4-5-20251001",
    "anthropic/claude-haiku-4-5",
    "us.anthropic.claude-haiku-4-5-20251001-v1:0",
    "claude-sonnet-4-6",
    "claude-opus-4-6",
  ])("%s still accepts sampling params", (id) => {
    expect(anthropicRejectsSamplingParams(id)).toBe(false);
  });

  it("does not false-match a longer family name by prefix", () => {
    // "opus-5" must not match "opus-50" and "fable-5" must not match "fable-55".
    expect(anthropicRejectsSamplingParams("claude-opus-50")).toBe(false);
    expect(anthropicRejectsSamplingParams("claude-fable-55")).toBe(false);
  });
});

describe("anthropicRejectsForcedToolChoice — Fable 5.1 (ggui#706)", () => {
  it("flags Fable 5.1 in every spelling", () => {
    expect(anthropicRejectsForcedToolChoice("claude-fable-5-1")).toBe(true);
    expect(anthropicRejectsForcedToolChoice("anthropic/claude-fable-5-1")).toBe(true);
    expect(anthropicRejectsForcedToolChoice("us.anthropic.claude-fable-5-1")).toBe(true);
  });

  it("does not flag Fable 5, Opus 5, Sonnet 5 or Haiku 4.5", () => {
    for (const id of ["claude-fable-5", "claude-opus-5", "claude-sonnet-5", "claude-haiku-4-5"]) {
      expect(anthropicRejectsForcedToolChoice(id)).toBe(false);
    }
  });
});

// ─── ggui#1254 — Opus 5.5, Mythos, every Bedrock profile, OpenRouter's dotted ids ───

describe("BEDROCK_INFERENCE_REGION_PREFIXES — the one region list (ggui#1254)", () => {
  it("is exactly the six AWS cross-region profile prefixes", () => {
    expect([...BEDROCK_INFERENCE_REGION_PREFIXES]).toEqual(["us", "eu", "au", "jp", "apac", "global"]);
  });
});

describe("normalizeAnthropicModelId — every region profile and the bedrock/ form (ggui#1254)", () => {
  it("strips every prefix in the list, and a bedrock/ prefix", () => {
    for (const region of BEDROCK_INFERENCE_REGION_PREFIXES) {
      expect(normalizeAnthropicModelId(`${region}.anthropic.claude-opus-5-5`)).toBe("claude-opus-5-5");
    }
    expect(normalizeAnthropicModelId("bedrock/global.anthropic.claude-opus-5-5")).toBe("claude-opus-5-5");
    expect(normalizeAnthropicModelId("bedrock/anthropic.claude-fable-5-1")).toBe("claude-fable-5-1");
    expect(normalizeAnthropicModelId("apac.anthropic.claude-fable-5-1")).toBe("claude-fable-5-1");
  });

  it("does not strip a prefix that is not an AWS profile", () => {
    expect(normalizeAnthropicModelId("xx.anthropic.claude-opus-5-5")).toBe("xx.anthropic.claude-opus-5-5");
  });
});

describe("anthropicRejectsForcedToolChoice — Fable 5.1, Mythos 5.1, Opus 5.5, Mythos Preview (ggui#1254)", () => {
  it("flags Opus 5.5 in every spelling — bare, anthropic/, anthropic., us., global., apac., bedrock/", () => {
    for (const id of [
      "claude-opus-5-5",
      "anthropic/claude-opus-5-5",
      "anthropic.claude-opus-5-5",
      "us.anthropic.claude-opus-5-5",
      "global.anthropic.claude-opus-5-5",
      "apac.anthropic.claude-opus-5-5",
      "bedrock/global.anthropic.claude-opus-5-5",
    ]) {
      expect(anthropicRejectsForcedToolChoice(id), id).toBe(true);
    }
  });

  it("flags Claude Mythos 5.1 and Mythos Preview, the rest of the forced-tool set in the API reference", () => {
    expect(anthropicRejectsForcedToolChoice("claude-mythos-5-1")).toBe(true);
    expect(anthropicRejectsForcedToolChoice("global.anthropic.claude-mythos-5-1")).toBe(true);
    expect(anthropicRejectsForcedToolChoice("claude-mythos-preview")).toBe(true);
  });

  it("flags OpenRouter's dotted spellings of both families", () => {
    expect(anthropicRejectsForcedToolChoice("anthropic/claude-opus-5.5")).toBe(true);
    expect(anthropicRejectsForcedToolChoice("anthropic/claude-fable-5.1")).toBe(true);
    expect(anthropicRejectsForcedToolChoice("global.anthropic.claude-fable-5-1")).toBe(true);
  });

  it("does not flag Opus 5, Fable 5, Mythos 5, a longer version number, or a non-Anthropic id", () => {
    for (const id of [
      "claude-opus-5",
      "claude-opus-5-50",
      "anthropic/claude-opus-5",
      "claude-mythos-5",
      "claude-fable-5",
      "openai/gpt-6-sol",
      "gpt-6-luna",
    ]) {
      expect(anthropicRejectsForcedToolChoice(id), id).toBe(false);
    }
  });
});

describe("anthropicRejectsSamplingParams — Opus 5.5 pinned explicitly (ggui#1254)", () => {
  it("flags claude-opus-5-5 in its API and Bedrock spellings", () => {
    expect(anthropicRejectsSamplingParams("claude-opus-5-5")).toBe(true);
    expect(anthropicRejectsSamplingParams("global.anthropic.claude-opus-5-5")).toBe(true);
  });
});

// ─── ggui#1268 — the forced-tool predicate pinned against the vendor over every routable Anthropic id ───

/**
 * Written from the vendor's pages, read 2026-09-23 — never from the predicate:
 *
 *   (A) platform.claude.com/docs/en/api/errors#forced-tool-use-not-supported —
 *       "Claude Opus 5.5, Claude Fable 5.1, and Claude Mythos 5.1 don't
 *       support forced tool use."
 *   (B) platform.claude.com/docs/en/about-claude/pricing#tool-use-pricing — the
 *       per-model "Tool choice" column: `auto`, `none` only, or `auto`, `none`
 *       then `any`, `tool`.
 *   (C) platform.claude.com/docs/en/agents-and-tools/tool-use/define-tools#forcing-tool-use —
 *       the restriction table, introduced as "Not every model and setting
 *       supports forced tool use. Where it isn't supported, …", naming exactly
 *       the three models in (A).
 *
 * Each `receipt` says which page decided the row and how: a row (B) lists, a
 * name (A) gives, or — only where (B) carries no row for the model — absence
 * from the restriction list (C) introduces as the exhaustive one.
 *
 * Keys are `normalizeAnthropicModelId` spellings, so a Bedrock or OpenRouter
 * spelling that normalizes to a distinct string (a `-v1:0` suffix, a dotted
 * version) is its own row.
 */
interface VendorForcedToolRow {
  readonly rejectsForcedToolChoice: boolean;
  readonly receipt: string;
}
const VENDOR_FORCED_TOOL_TABLE: Readonly<Record<string, VendorForcedToolRow>> = {
  "claude-fable-5-1": { rejectsForcedToolChoice: true, receipt: "(A) names Claude Fable 5.1; (C) lists it" },
  "claude-opus-5-5": {
    rejectsForcedToolChoice: true,
    receipt: "(A) names Claude Opus 5.5; (B) Claude Opus 5.5 = `auto`, `none` only",
  },
  "claude-fable-5": {
    rejectsForcedToolChoice: false,
    receipt: "absent from (A) and from (C)'s restriction list; (B) has no Fable row",
  },
  "claude-opus-5": { rejectsForcedToolChoice: false, receipt: "(B) Claude Opus 5 = `auto`, `none` / `any`, `tool`" },
  "claude-sonnet-5": { rejectsForcedToolChoice: false, receipt: "(B) Claude Sonnet 5 = `auto`, `none` / `any`, `tool`" },
  "claude-haiku-4-5-20251001": {
    rejectsForcedToolChoice: false,
    receipt: "(B) Claude Haiku 4.5 = `auto`, `none` / `any`, `tool`",
  },
  "claude-opus-4-8": { rejectsForcedToolChoice: false, receipt: "(B) Claude Opus 4.8 = `auto`, `none` / `any`, `tool`" },
  "claude-sonnet-4-6": {
    rejectsForcedToolChoice: false,
    receipt: "(B) Claude Sonnet 4.6 = `auto`, `none` / `any`, `tool`",
  },
  "claude-opus-4-7": { rejectsForcedToolChoice: false, receipt: "(B) Claude Opus 4.7 = `auto`, `none` / `any`, `tool`" },
  "claude-opus-4-6": { rejectsForcedToolChoice: false, receipt: "(B) Claude Opus 4.6 = `auto`, `none` / `any`, `tool`" },
  "claude-haiku-4-5-20251001-v1:0": {
    rejectsForcedToolChoice: false,
    receipt: "Bedrock spelling of Claude Haiku 4.5 — (B) `any`, `tool`",
  },
  "claude-opus-4-6-v1": {
    rejectsForcedToolChoice: false,
    receipt: "Bedrock spelling of Claude Opus 4.6 — (B) `any`, `tool`",
  },
  "claude-haiku-4.5": {
    rejectsForcedToolChoice: false,
    receipt: "OpenRouter spelling of Claude Haiku 4.5 — (B) `any`, `tool`",
  },
  "claude-sonnet-4.6": {
    rejectsForcedToolChoice: false,
    receipt: "OpenRouter spelling of Claude Sonnet 4.6 — (B) `any`, `tool`",
  },
  "claude-opus-4.7": {
    rejectsForcedToolChoice: false,
    receipt: "OpenRouter spelling of Claude Opus 4.7 — (B) `any`, `tool`",
  },
};

/**
 * Every Anthropic id a route can name, in every spelling the allowlists
 * carry: the direct API list, the Anthropic ids on Bedrock (bare `anthropic.`
 * or behind a region profile), and OpenRouter's `anthropic/` routes.
 *
 * Residual, deliberately outside this pin: ids no allowlist carries — Claude
 * Mythos 5.1 and Claude Mythos Preview (limited availability), and an
 * arbitrary `anthropic/…` string passed through OpenRouter's open escape
 * hatch. The predicate still matches Mythos 5.1 and Mythos Preview, pinned by
 * the ggui#1254 block above; (A) names Mythos 5.1 and not Mythos Preview, and
 * a wrong `true` is the safe direction.
 */
const ROUTABLE_ANTHROPIC_IDS: readonly string[] = [
  ...MODELS.anthropic,
  ...MODELS.bedrock.filter((id) => id.startsWith("anthropic.") || id.includes(".anthropic.")),
  ...MODELS.openrouter.filter((id) => id.startsWith("anthropic/")),
];
const ROUTABLE_NORMALIZED = [...new Set(ROUTABLE_ANTHROPIC_IDS.map(normalizeAnthropicModelId))].sort();

describe("anthropicRejectsForcedToolChoice — pinned against the vendor over every routable Anthropic id (ggui#1268)", () => {
  it("the routable union is 15 distinct spellings — a new routable Anthropic id changes this number, and this name", () => {
    expect(ROUTABLE_NORMALIZED).toHaveLength(15);
  });

  it("every routable Anthropic id has a vendor-quoted row — a new one without a receipt fails here", () => {
    const unclassified = ROUTABLE_NORMALIZED.filter((id) => !(id in VENDOR_FORCED_TOOL_TABLE));
    expect(unclassified).toEqual([]);
  });

  it("every vendor row names a routable id — a row for a model no route can reach is stale", () => {
    const stale = Object.keys(VENDOR_FORCED_TOOL_TABLE).filter((id) => !ROUTABLE_NORMALIZED.includes(id));
    expect(stale).toEqual([]);
  });

  it("the predicate agrees with the vendor on every routable spelling, in both directions", () => {
    const rows = Object.values(VENDOR_FORCED_TOOL_TABLE);
    // Both directions are exercised, not just one: the table holds both answers.
    expect(rows.filter((r) => r.rejectsForcedToolChoice)).toHaveLength(2);
    expect(rows.filter((r) => !r.rejectsForcedToolChoice)).toHaveLength(13);
    for (const raw of ROUTABLE_ANTHROPIC_IDS) {
      const row = VENDOR_FORCED_TOOL_TABLE[normalizeAnthropicModelId(raw)];
      expect(row, raw).toBeDefined();
      if (row === undefined) continue;
      expect(anthropicRejectsForcedToolChoice(raw), `${raw} — ${row.receipt}`).toBe(row.rejectsForcedToolChoice);
    }
  });
});
