// Generated by scripts/renderer-digest.mjs. Do not edit: run
// `pnpm --filter @ggui-ai/brand generate:digest` after changing the renderer.

/** A sha256 over the social card renderer's sources and face files. */
export const SOCIAL_CARD_RENDERER_DIGEST = 'a841dece5723b88f7c3bbb21921e732c8dfe73450b3496daa90a35e8ca3791a8';
