/**
 * OAuth 2.1 + PKCE + DCR flow simulator — Tier 2 mirror of what an
 * MCP-Apps-aware host (claude.ai et al.) does when it hits a 401 from
 * the MCP endpoint and walks the RFC discovery chain to obtain a
 * Bearer token.
 *
 * Spec coverage:
 *   - RFC 9728  protected resource metadata
 *   - RFC 8414  authorization server metadata
 *   - RFC 7591  Dynamic Client Registration
 *   - RFC 7636  PKCE (S256)
 *   - RFC 6749  authorization code grant
 *   - RFC 8707  resource indicators (S4.2 in oauth.ts)
 *
 * Real claude.ai opens a browser at the /authorize URL for user
 * consent; the simulator skips the chrome and POSTs the form
 * directly with `api_key=<bearer>` (the OSS server's paste-key
 * shape). For tests against `devAllowAll` adapters any non-empty
 * key passes; production-shape tests pass a real `ggui_user_*` key.
 *
 * Where possible methods mirror the field names from each spec so
 * tests reading the simulator's return shapes can cross-reference
 * the RFC directly.
 */
import { createHash, randomBytes } from 'node:crypto';

/** RFC 9728 — protected-resource metadata document. */
export interface ProtectedResourceMetadata {
  readonly resource: string;
  readonly authorization_servers: readonly string[];
}

/** RFC 8414 — authorization-server metadata document (subset we use). */
export interface AuthorizationServerMetadata {
  readonly issuer: string;
  readonly authorization_endpoint: string;
  readonly token_endpoint: string;
  readonly registration_endpoint: string;
  readonly response_types_supported: readonly string[];
  readonly grant_types_supported: readonly string[];
  readonly code_challenge_methods_supported: readonly string[];
  readonly token_endpoint_auth_methods_supported: readonly string[];
  readonly scopes_supported?: readonly string[];
}

/** RFC 7591 — DCR response (subset). */
export interface DcrResponse {
  readonly client_id: string;
  readonly redirect_uris: readonly string[];
  readonly grant_types?: readonly string[];
  readonly response_types?: readonly string[];
  readonly token_endpoint_auth_method?: string;
  readonly client_name?: string;
}

/** PKCE pair — verifier (kept by client) + S256 challenge (sent on /authorize). */
export interface PkcePair {
  readonly codeVerifier: string;
  readonly codeChallenge: string;
  readonly codeChallengeMethod: 'S256';
}

/** Result of the /authorize POST round-trip. Errors carry `error` only. */
export type AuthorizeResult =
  | { readonly code: string; readonly state?: string }
  | { readonly error: string; readonly status: number; readonly html?: string };

/** Result of /token. */
export interface TokenResult {
  readonly accessToken: string;
  readonly tokenType: string;
  readonly scope?: string;
}

export interface OAuthFlowSimulatorOptions {
  /** Base URL of the MCP server — same shape as `HostSimulator.url`. */
  readonly url: string;
  /**
   * Path of the protected-resource doc. Defaults to
   * `/.well-known/oauth-protected-resource`. For per-app discovery
   * use `/apps/<appId>/.well-known/oauth-protected-resource`.
   */
  readonly protectedResourcePath?: string;
}

export interface RegisterArgs {
  readonly clientName?: string;
  readonly redirectUris: readonly string[];
}

export interface SubmitAuthorizeArgs {
  readonly clientId: string;
  readonly redirectUri: string;
  /** Generated by `generatePkcePair()` if omitted. */
  readonly codeVerifier?: string;
  readonly codeChallenge?: string;
  /** Opaque round-trip value — caller asserts the redirect echoes it. */
  readonly state?: string;
  /** RFC 8707 §2 — resource indicator (URI of the MCP endpoint). */
  readonly resource?: string;
  /**
   * Either `apiKey` (paste-key path) OR `pairCode` (CLI pair path)
   * must be set. Real claude.ai users paste an API key; CLI flows
   * type the short code printed on the terminal.
   */
  readonly apiKey?: string;
  readonly pairCode?: string;
  /**
   * Authorize-endpoint URL. Defaults to the discovered AS metadata's
   * `authorization_endpoint`. Override for tests asserting a specific
   * URL (e.g. per-app endpoints).
   */
  readonly authorizeEndpoint?: string;
}

export interface ExchangeTokenArgs {
  readonly code: string;
  readonly codeVerifier: string;
  readonly clientId: string;
  readonly redirectUri: string;
  readonly resource?: string;
  /** Override the discovered token_endpoint. */
  readonly tokenEndpoint?: string;
}

export interface RunFullFlowArgs {
  readonly apiKey: string;
  /** RFC 8707 — same value forwarded onto /authorize AND /token. */
  readonly resource?: string;
  /** Defaults to a stable in-test value. */
  readonly redirectUri?: string;
  readonly clientName?: string;
  readonly state?: string;
}

export interface RunFullFlowResult {
  readonly accessToken: string;
  readonly clientId: string;
  readonly prDoc: ProtectedResourceMetadata;
  readonly asMeta: AuthorizationServerMetadata;
  readonly pkce: PkcePair;
  readonly state?: string;
}

/**
 * Generate a PKCE pair (RFC 7636). The verifier is 43-128 chars from
 * the unreserved set; we use 32 random bytes → base64url ≈ 43 chars.
 */
export function generatePkcePair(): PkcePair {
  const codeVerifier = randomBytes(32).toString('base64url');
  const codeChallenge = createHash('sha256').update(codeVerifier).digest('base64url');
  return { codeVerifier, codeChallenge, codeChallengeMethod: 'S256' };
}

/**
 * Drives the OAuth code-flow against an MCP server's mounted OAuth
 * routes. Independent of {@link HostSimulator} — tests can use the
 * resulting `access_token` to bootstrap a HostSimulator instance.
 */
export class OAuthFlowSimulator {
  private readonly opts: OAuthFlowSimulatorOptions;
  private cachedPrDoc: ProtectedResourceMetadata | null = null;
  private cachedAsMeta: AuthorizationServerMetadata | null = null;

  constructor(opts: OAuthFlowSimulatorOptions) {
    this.opts = opts;
  }

  /**
   * Fetch RFC 9728 protected-resource metadata. Cached after first
   * fetch — the doc doesn't change mid-test.
   */
  async discoverProtectedResource(): Promise<ProtectedResourceMetadata> {
    if (this.cachedPrDoc) return this.cachedPrDoc;
    const path =
      this.opts.protectedResourcePath ?? '/.well-known/oauth-protected-resource';
    const res = await fetch(`${this.opts.url}${path}`);
    if (!res.ok) {
      throw new Error(`PR metadata fetch failed: ${res.status} ${res.statusText}`);
    }
    const doc = (await res.json()) as ProtectedResourceMetadata;
    this.cachedPrDoc = doc;
    return doc;
  }

  /**
   * Fetch RFC 8414 authorization-server metadata. The `issuer`
   * defaults to the first `authorization_servers` entry in the PR
   * doc — call {@link discoverProtectedResource} first OR pass it in.
   */
  async discoverAuthorizationServer(
    issuer?: string,
  ): Promise<AuthorizationServerMetadata> {
    if (this.cachedAsMeta) return this.cachedAsMeta;
    let issuerUrl = issuer;
    if (!issuerUrl) {
      const pr = await this.discoverProtectedResource();
      issuerUrl = pr.authorization_servers[0];
      if (!issuerUrl) {
        throw new Error('PR doc has no authorization_servers');
      }
    }
    const res = await fetch(
      `${issuerUrl}/.well-known/oauth-authorization-server`,
    );
    if (!res.ok) {
      throw new Error(
        `AS metadata fetch failed: ${res.status} ${res.statusText}`,
      );
    }
    const meta = (await res.json()) as AuthorizationServerMetadata;
    this.cachedAsMeta = meta;
    return meta;
  }

  /**
   * RFC 7591 — POST /oauth/register. Returns the issued client
   * record. The caller MUST persist `client_id` for /authorize.
   */
  async register(args: RegisterArgs): Promise<DcrResponse> {
    const asMeta = await this.discoverAuthorizationServer();
    const res = await fetch(asMeta.registration_endpoint, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({
        redirect_uris: [...args.redirectUris],
        ...(args.clientName !== undefined ? { client_name: args.clientName } : {}),
      }),
    });
    if (res.status !== 201) {
      const errBody = await res.text();
      throw new Error(`DCR failed: ${res.status} ${errBody}`);
    }
    return (await res.json()) as DcrResponse;
  }

  /**
   * POST /oauth/authorize with the OAuth params + paste-key. Real
   * claude.ai goes through GET /authorize → user-paste → POST; the
   * simulator collapses to a direct POST since there's no browser.
   *
   * Follows the `Location` header on the 302 redirect manually so
   * the caller can extract `code` + `state` from the returned URL
   * without an HTTP client that auto-follows + drops the redirect's
   * Location.
   */
  async submitAuthorize(args: SubmitAuthorizeArgs): Promise<AuthorizeResult> {
    if (!args.apiKey && !args.pairCode) {
      throw new Error('submitAuthorize requires `apiKey` or `pairCode`');
    }
    const asMeta = await this.discoverAuthorizationServer();
    const endpoint = args.authorizeEndpoint ?? asMeta.authorization_endpoint;

    let codeVerifier = args.codeVerifier;
    let codeChallenge = args.codeChallenge;
    if (!codeVerifier || !codeChallenge) {
      const pkce = generatePkcePair();
      codeVerifier = pkce.codeVerifier;
      codeChallenge = pkce.codeChallenge;
    }

    const form = new URLSearchParams();
    form.set('response_type', 'code');
    form.set('client_id', args.clientId);
    form.set('redirect_uri', args.redirectUri);
    form.set('code_challenge', codeChallenge);
    form.set('code_challenge_method', 'S256');
    if (args.state !== undefined) form.set('state', args.state);
    if (args.resource !== undefined) form.set('resource', args.resource);
    if (args.apiKey !== undefined) form.set('api_key', args.apiKey);
    if (args.pairCode !== undefined) form.set('pair_code', args.pairCode);

    const res = await fetch(endpoint, {
      method: 'POST',
      headers: { 'content-type': 'application/x-www-form-urlencoded' },
      body: form.toString(),
      redirect: 'manual',
    });

    if (res.status >= 400) {
      const html = await res.text();
      return { error: 'authorize_failed', status: res.status, html };
    }
    if (res.status !== 302 && res.status !== 303) {
      const html = await res.text();
      return {
        error: `unexpected_status_${res.status}`,
        status: res.status,
        html,
      };
    }
    const location = res.headers.get('location');
    if (!location) {
      return { error: 'no_location_header', status: res.status };
    }
    const url = new URL(location);
    const code = url.searchParams.get('code');
    if (!code) {
      return { error: 'no_code_in_redirect', status: res.status };
    }
    const state = url.searchParams.get('state') ?? undefined;
    return { code, ...(state !== undefined ? { state } : {}) };
  }

  /**
   * POST /oauth/token — exchange code + verifier for access token.
   * Mirrors RFC 6749 §4.1.3 + RFC 8707 §2.2 for the optional
   * `resource` echo on the token request.
   */
  async exchangeToken(args: ExchangeTokenArgs): Promise<TokenResult> {
    const asMeta = await this.discoverAuthorizationServer();
    const endpoint = args.tokenEndpoint ?? asMeta.token_endpoint;

    const form = new URLSearchParams();
    form.set('grant_type', 'authorization_code');
    form.set('code', args.code);
    form.set('redirect_uri', args.redirectUri);
    form.set('client_id', args.clientId);
    form.set('code_verifier', args.codeVerifier);
    if (args.resource !== undefined) form.set('resource', args.resource);

    const res = await fetch(endpoint, {
      method: 'POST',
      headers: { 'content-type': 'application/x-www-form-urlencoded' },
      body: form.toString(),
    });
    const body = (await res.json()) as Record<string, unknown>;
    if (!res.ok) {
      const code = (body['error'] as string) ?? `http_${res.status}`;
      const desc = (body['error_description'] as string) ?? 'token exchange failed';
      throw new Error(`token error: ${code} — ${desc}`);
    }
    return {
      accessToken: body['access_token'] as string,
      tokenType: (body['token_type'] as string) ?? 'Bearer',
      ...(typeof body['scope'] === 'string' ? { scope: body['scope'] as string } : {}),
    };
  }

  /**
   * Convenience composer — discovery → DCR → /authorize → /token.
   * Returns the access token plus every intermediate doc/state so
   * tests can assert on any step without re-running the flow.
   */
  async runFullFlow(args: RunFullFlowArgs): Promise<RunFullFlowResult> {
    const redirectUri = args.redirectUri ?? 'https://client.example/cb';
    const prDoc = await this.discoverProtectedResource();
    const asMeta = await this.discoverAuthorizationServer();
    const dcr = await this.register({
      ...(args.clientName !== undefined ? { clientName: args.clientName } : {}),
      redirectUris: [redirectUri],
    });
    const pkce = generatePkcePair();
    const authorize = await this.submitAuthorize({
      clientId: dcr.client_id,
      redirectUri,
      codeVerifier: pkce.codeVerifier,
      codeChallenge: pkce.codeChallenge,
      ...(args.state !== undefined ? { state: args.state } : {}),
      ...(args.resource !== undefined ? { resource: args.resource } : {}),
      apiKey: args.apiKey,
    });
    if ('error' in authorize) {
      throw new Error(
        `authorize failed (${authorize.status}): ${authorize.error}` +
          (authorize.html ? ` — ${authorize.html.slice(0, 200)}` : ''),
      );
    }
    const token = await this.exchangeToken({
      code: authorize.code,
      codeVerifier: pkce.codeVerifier,
      clientId: dcr.client_id,
      redirectUri,
      ...(args.resource !== undefined ? { resource: args.resource } : {}),
    });
    return {
      accessToken: token.accessToken,
      clientId: dcr.client_id,
      prDoc,
      asMeta,
      pkce,
      ...(authorize.state !== undefined ? { state: authorize.state } : {}),
    };
  }
}
