import { useContext } from 'react';
import type { Context } from 'react';

/**
 * Read `[value, setter]` for a declared `contextSpec` slot. The
 * iframe runtime owns the underlying `useState` and seeds each
 * Provider; the boilerplate auto-generates one `useGguiContext`
 * call per declared slot at the top of the component body, so the LLM
 * has `slotName` + `setSlotName` in scope without writing any
 * `useState` or `<Provider>` itself.
 *
 * Direction: client → agent (one-way). Every value change is mirrored
 * to the host LLM's context (debounced) by the runtime.
 *
 * **Throws synchronously** when the slot isn't registered. This is a
 * fail-loud signal: the boilerplate destructure drifted from the
 * contract, OR `contextSpec` doesn't declare the slot, OR the runtime
 * hasn't installed the Context registry yet. Authors should see the
 * error message and fix one of those three sites — silent fallback
 * would mask an architectural bug.
 *
 * @example
 * ```tsx
 * // boilerplate auto-prepends:
 * const [currentStep, setCurrentStep] =
 *   useGguiContext<number>('currentStep');
 *
 * // LLM body:
 * <Button onClick={() => setCurrentStep((s) => s + 1)}>Next</Button>
 * ```
 *
 * @public
 */
export function useGguiContext<T>(
  slotName: string,
): readonly [T, (next: T | ((prev: T) => T)) => void] {
  // Slot keys are camelCase in `contextSpec`; the runtime registers
  // each Context under its PascalCase derived name (e.g.
  // `'currentStep'` → `'CurrentStepContext'`). Mirror the protocol's
  // `deriveContextName` here. We do NOT import from
  // `@ggui-ai/protocol/integrations/mcp-apps` to keep the wire
  // package's runtime surface minimal — it's a four-line transform,
  // and the equivalent test in `mcp-apps.test.ts` pins the rule.
  const contextName =
    slotName.length === 0
      ? 'Context'
      : slotName.charAt(0).toUpperCase() + slotName.slice(1) + 'Context';

  const registry = (
    globalThis as {
      __ggui__?: {
        contexts?: Record<
          string,
          Context<readonly [unknown, (next: unknown) => void]>
        >;
      };
    }
  ).__ggui__?.contexts;
  const ctx = registry?.[contextName];
  if (!ctx) {
    throw new Error(
      `[ggui] useGguiContext('${slotName}'): no Context registered. ` +
        `The contract must declare 'contextSpec.${slotName}' AND the ` +
        `runtime must have synthesized the per-slot React Context at ` +
        `boot. If you see this in production code generated by the ` +
        `LLM, the boilerplate's destructure line drifted from the ` +
        `contract.`,
    );
  }
  // The runtime's SingleSlotProvider mounts every Provider with a
  // value of shape `[value, setValue] as const`. The cast at the
  // useContext seam narrows the registry's loose type back to the
  // typed tuple the caller asked for. NOT a workaround — the registry
  // is by-design open-ended (one Context per declared slot, each with
  // its own value type).
  return useContext(ctx) as readonly [T, (next: T | ((prev: T) => T)) => void];
}
