/**
 * Trait composition — the `as` prop type model.
 *
 * A *trait* is a behavior mixin — `Clickable`, `Hoverable`, `Pressable`
 * — that a primitive composes via `as`:
 *
 *   <Card as={Clickable} onClick={handler}>…</Card>
 *
 * The primitive stays itself; the trait layers interaction (handlers,
 * keyboard a11y, hover/active styling) on top — *orthogonally*, as a
 * prop, with no change to the JSX tree shape. Composing behaviour via a
 * prop (not a wrapper element) keeps an LLM's edits prop-local: adding
 * interactivity never forces a structural re-nest.
 *
 * ## Why `as` is closed-world (a `TraitComponent`, never `ElementType`)
 *
 *   - It keeps the polymorphic typing tractable — the variant union is
 *     generated from a known, small set.
 *   - It preserves the guardrail: a bare primitive (no `as`) exposes
 *     ONLY its own props. A raw `onClick` on `<Card>` stays a type
 *     error — the interaction affordance is reachable solely by opting
 *     into a trait, which carries the keyboard + ARIA wiring with it.
 *
 * Element substitution ("render the root as a different tag",
 * `as="section"`) is a SEPARATE concern and does NOT belong on `as`.
 */
import {
  createElement,
  type ComponentPropsWithoutRef,
  type CSSProperties,
  type ReactElement,
  type ReactNode,
} from 'react';
import { Clickable } from './Clickable';
import { Hoverable } from './Hoverable';
import { Pressable } from './Pressable';

/**
 * The closed set of trait components composable onto a primitive via
 * `as`. Adding a trait: add its component to this union — every
 * primitive that types its props with {@link WithTrait} then accepts
 * it automatically, with no per-primitive edit.
 */
export type TraitComponent =
  | typeof Clickable
  | typeof Hoverable
  | typeof Pressable;

/**
 * The props a trait *contributes* to its host when applied via `as` —
 * the behaviour props only (`onClick`, `hoverStyle`, `cursor`, …).
 *
 * `children` / `style` / `className` are omitted: those stay
 * host-owned (the host's resolved `style` flows onto the trait at
 * render time; see {@link renderWithTrait}). Omitting `children` also
 * sidesteps `Pressable`'s render-prop `children` overload, which a
 * host's plain `ReactNode` children can't satisfy.
 *
 * `ComponentPropsWithoutRef` so the host never inherits a `ref` it
 * does not forward.
 */
export type TraitProps<T extends TraitComponent> = Omit<
  ComponentPropsWithoutRef<T>,
  'children' | 'style' | 'className'
>;

/**
 * One `as={SomeTrait}` branch of {@link WithTrait}. Distributes over
 * the {@link TraitComponent} union: `T` is a naked type parameter, so
 * `TraitVariant<Own, TraitComponent>` expands to one branch per trait.
 */
type TraitVariant<Own, T> = T extends TraitComponent
  ? Own & { readonly as: T } & TraitProps<T>
  : never;

/**
 * A primitive's public prop type once trait composition is layered on.
 *
 * A discriminated union on `as`:
 *   - `as` omitted     → `Own` only — a bare primitive (raw event
 *                        handlers here are a type error, by design).
 *   - `as={SomeTrait}` → `Own` + that trait's props (`onClick`, …).
 *
 * The trait branches are generated by distributing over
 * {@link TraitComponent}, so a new trait extends every primitive's
 * `as` for free.
 */
export type WithTrait<Own> =
  | (Own & { readonly as?: never })
  | TraitVariant<Own, TraitComponent>;

/**
 * Render a div-rooted primitive's root element, composing a trait when
 * `as` is set:
 *
 *   - no trait  → a plain `<div>` carrying the primitive's resolved
 *                 `style` + `className`.
 *   - `as={T}`  → the trait component IS the root: the primitive's
 *                 `style` / `className` flow onto it and the trait's
 *                 own props (`onClick`, `hoverStyle`, …) ride through.
 *
 * `createElement` (not JSX) is deliberate — it sidesteps the
 * correlated-union narrowing JSX cannot do when `trait` and
 * `traitProps` are a discriminated pair. One runtime, shared by every
 * div-rooted primitive (Box, Stack, Card) so trait composition lives
 * in exactly one place.
 */
export function renderWithTrait(
  trait: TraitComponent | undefined,
  traitProps: TraitProps<TraitComponent>,
  root: { readonly className?: string; readonly style: CSSProperties },
  children: ReactNode,
): ReactElement {
  if (trait === undefined) {
    return createElement(
      'div',
      { className: root.className, style: root.style },
      children,
    );
  }
  return createElement(
    trait,
    { ...traitProps, className: root.className, style: root.style },
    children,
  );
}
